kind: Deployment
apiVersion: apps/v1
metadata:
  name: goaws
spec:
  replicas: 1
  selector:
    matchLabels:
      name: goaws
  template:
    metadata:
      labels:
        name: goaws
    spec:
      serviceAccountName: goaws
      containers:
      - image: scottaubrey/goaws:latest
        name: goaws
        ports:
        - name: http
          containerPort: 4100
