apiVersion: v1
kind: Service
metadata:
  name: sns
  labels:
    app: goaws
spec:
  type: ClusterIP
  ports:
    - port: 4100
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: goaws
