apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: data-hub
spec:
  encryptedData:
    credentials: AgCssBRnOF9bdCymfhrrW2sIOckcQgU3cMHPLcHAJ1g0nByacjrVOMfwO/daWY1qNlkCcA3pDACEflYKVEOPG8Dcq+hZOFCnz3kZCfDNU6jAGP19FBGk7NJVmrP8auDwKj8Ln2lCX02v8n9vefouJdnEsn3i2NLKxtxatDqtkIS8cniJc4pA4bouhTmRZgr+qiCT4vUPlQoKJXA+8TO+wF68FIOIpqMSM9mh/tkBVaC03zvjTRrKtmfHgyirIkXLUKNjUZohpmiQj9bTeCi8tGo0BbXMXchb9RM5jjfZoSYKlThN5vZYXmeChuNzhNL48rbCMWhx+ZJegKPOoU94dm6gIJ68H37yiwrLziPVZUCl98Qxy2czv+2P6Zy5baRKli2OwNEFS1OCcfNK79cGvIl3r/Q9qfBhownInCGO7hZaekJGpEHvg21f+of5UFAbFpPlU2G10XPj+lVe5oPbigEEIICji0BloBLeGVvZxr9IL7LqNCvlt8/nOj0U5ENEh2rl84HMD/7dfaI3z224AiznvTN0w9MXzcpeaCLpjnOCR18MvqmpeYwu0kDRc4RTb+CbcfKAbKDscxYFWAxLzcMN9eutJdfskQsRjeT9Z4QJJwbky/Hux8hLmFHq7qd+fIovc0OXdcQmNbgqCA6jlnTz8wRWUrWom8rlhShk5tzZIIW/gTW6f+u1DxEETQOGeJ5/aOIIZVE5AfQIutu/bw8zg4u0dgE9tdNWpiqJTWhYhig1SNII/FJEhkrmZjgYVak0APiJuqyRVuFRgpHoZ0wJA0C5lRxyvzazNx0zA32IvYhfFZGNjbP/XsWDdDvo3IYCTZKPVzpx7eAAE9hKVhat8yC7CxvdfKtziKQI3i6FP1PNvoR3ASs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: data-hub
    type: Opaque

