apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gcloud
  namespace: data-hub
spec:
  encryptedData:
    credentials.json: AgBLK9dZ2b4hJrezq02MlaiK/e99HQiRVDYcStwdvp8zEekQBGGTNQzpxetN3lm0Le7DtrRybb/yqw3saQALG+7xpXHbftoo/8fzD6oym2gTmlDsBP+Ix5qSN+O6KM3TRIO/3/iWTw7jsYzkh3nKpw/uCaQdPwpgQjnC/JWZwo9nvzBw3rde6cyyh0YwpO2Mc9GqNjUMaTvyS0haBfae1/EBDSZtoB3A1XJQB98NQnjP9QDgJ8oRqdZn4Q9dkYhPz0W/yEGm/336F6tFHPqiSiqJHdwyCG1Wersup9RjuFCFBIV5/jZgVOUU1Q7Ibtqieq4LJTGzgj6W9pMmQRJShNSqflSJdp/MvOXuhyMGZr/61VCRAN4X1iJ6XBBjrK6GG/xMI6mdc23nyvCUmywK7xa0Zfzc2fz1aeBP/ASG/PYvlXqGUTl5Cp4l7/2+NJwMJv76Ga77KE729hvWaURud9hMIJbCXfjtNMpumcTgT1dIBSH3EBwUREXnNUV8wE7zKYFyhgLXeREmbm9HFb9Bd6QYLIEQqEwgMgMJkw1ckywRNWnlfVdEOcnKRLdmSMbamiz0j+/75dzXn6RazWd998HZ0NPfUyQdjEPwcKzSgluzGLPjhm7PehDYs31E8yRLZtgR6860VrzD4jstTN1zPMeGobFUF0MbE1hR28Ihq4jQ0xspCKYeBclAyLp5YLsngPaNIqVURe0tO/F9hN5NJv2/Ww0Kkr4QskVMA0g376KZEMxBiwVFJYQUW3rskM9NSHstZqEGsUEe1pUbrg4h9AJt8aSvag3TlGiE3FUrLkq3whuB9pBRCr46mExwo+O67C3yArWRVHcx9sUF//tAOjXg51L7YsNCL2rm5sfIkMx/8MQfeThnj8T1I94pnn30wMgGRCYnR5pYTlPvyXOGsXzwaa0weL5ppc9oq8rLfDuPO58zbJGJAQ2KN48uOD8oHklK0svBRnk3t8POI0RpE2cegjMrRoNcZsh8oxIXfbOXwOJ5zjRQsByzmNVC/mOw5vijC/JlLYiUzefij/Tjs5/1hO6grU7TuG0RDx7AK/B1KD+1fQEEGgi8IAmioMd9rb+Q06B7KVgFSyNAZ5hx+KW6VNnkqy2Pb2ivv4dAsEpArZT9XRpWEqyxvoG1jw855jBWrjCPPeY8eoDQSxYqAW38wsp2fUeceIqTPqKKB0G5Qzq0UceM98P2YPPPJn2uBcXpeC014glqVUyPFIUEqSQRNvXjASGCzD3PeRvgAaI5YdLFZePAzv5DfNUgtV+at8Wa2IBIlXdij9Ure2iCpjrS7oBODvrNW9bq5q630VW4EVawhTQ/MXsy8xgClTZrf5KudLRs2GRyed9r/qpgI4kHXsCYNUSzLt/xWsyMj4PEcsnevDRnz40wUFIUbWVN1/X9Hy4R9M36KAsCRwfdVsc4dYji0RAN1vsthnsifzskn+WSb6OaQWVV8pBcuDeckTO/EE6am14Or0+6xaZvPP7uq+eeBatVu9lXzEFT5WKko51OWQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gcloud
      namespace: data-hub
    type: Opaque

