apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-auth
  namespace: data-hub
spec:
  encryptedData:
    AIRFLOW__GOOGLE__CLIENT_ID: AgCsaDdJJ4eyk1AmLkIkeLT9rJpxlAsBdNz89ES4bKJM3dcMEKESobtearbBlYqgQ6GLnBMGlkSXCPY1NFWxP+aEIoVa9/Q9KdOkTEUYrbqjdzKBm6nSnHe9Co0Vj8ov0UgOwrqnFOwnZospFR8KlA3Klm3OrnlV4AHs5xXWYIKuIielNUfM8iNuyHlic+aXAAW/Ms+fJhAZL+j77Nt74BbaOBNqvkX2cc3MxZQxwcwoorPNc5IF8Vq6QTEMiTh9zRwaH2GW0oqAcJ1qPs6H6HtOpxCf7pFiWGY9Pkz0UT4fLq399r/5fnh4LvhVvH17CcqYHQjsDuHkWQ+UcKc6n2HUdwNOM7/CXpSs+sKhWNm4DzCCGa5vNz1xp/uXmD3Qb2+yc1d0LZCrNI+Cc+Yxou5cXCoAeEJQRG1UJozSPGG1N//3v5uxpQaJG5IpCZtIlBC7qD8CLZEgb3kwgPvMWr6NNGzSx/2a6SS39c2vYBb+rD7ES3R2S92VkP535bqUJADopQlUFf9KnD+crjB/jdsZYiV78KzzR1gRRX7h6AJrtD0GkCSHX5dvrUFeklbLd4G4skO8aZGVCuoHDRFokxlKJY3h7gw632r3a4Z0v5gZYK+KRQ4V34DkBtDF20lE+KV15tlyVMjJUt4lzaJQbcOmGTa2Ir6ebpOnCzryRGU/u/nFdKFmWlzpkCJwOUmJpreYGpDFcZ8gv4BQVprNOpizdH8bSt4l6BuxdKpS3LEEXnlhm+j7gKYrefEgWggUHQVRawAGdYSsXv5/od4nq/iVZbritYHwEeQ=
    AIRFLOW__GOOGLE__CLIENT_SECRET: AgAhNNCdHdERI/Im4t5KkKdE3ViWw9RYHvO+HFGmTcABjO7bfLO3MOEo2ypSQHsUHpGEn0RFLbe/HetpdJjiienAY9aSgZVuLF5kXyQQkNaTay/jzHlhs/Z9/gnO8MT+t8PxrIfy7wvI87Rn64xTLTUfiwf8kmniCiPkUSBxbEgOF3vtpOk6v+In58ulyZqOp/0mg1Fqw0S4gRmXqVa79IOV2ov7To+MzMKYSgijY8+gIeMwmDp4V3vQYupdq6WBnWBMOGqoahWK7RtPbMqZ7QAUnvsVgE/wHyK5WICEVbsBiqk9mtOlyCPezEnhegkwRmQqzzzKXe9fr3neRQw9vTqkEkmihQ5FCtyv+sbvSzxGtlTeatALQWPEK3+ioxd9H19LPjPDjX8la5meUJw91Vp8YFA0xN7/ASJrJNoj1M8AyJsd7H/bXEArp2/0ywT0hev3SJ+1Y/TMXPD7hG56gbD8J63txI2V1AjrT6Z+/twwgt4glMpe5PUa7OBm9OlrsJoyn+Fu33mNXCmUUk69iSu9vXKdqFYWiGs62tOlkbvwKShgq3Wi+asgsNTV8tffozjeLXukbFN/rZD+05z9D4ZHXf+Mce+ExA4hxcRTPWwF0gDdQrigleQllDNtciVN+QHNdkaDjdtTp1Ky8dxuCTlFcJDvjwWemO+ieQ7XufGOGUAwZOvS8B1+qYlorHqdUy8W5vbi0m8AigteDLdz/ctrxs6RRDrHFGeI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: google-auth
      namespace: data-hub
    type: Opaque

