apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: toggl
  namespace: data-hub
spec:
  encryptedData:
    toggl_api_token.txt: AgBYBP0ILKRU6NjHp+BXXmstvTUBePhA/AiQ7rkufLg53FatUWQqBFciuCYg7y8dCt07hgu9Kaw/PZPVGZlpO4tF4SIwyU+tW+oZ478bDpelr9trppF6Cnq/P8cvooRsVRx48JmpzkPhyXPVYcVTUj+WbOO4vkJVDcEIV+MYiAD1tVMHo/XEKnzyDiad7XO7/j0xevk/X7i4xbgZ2hd6lsYgdLfB3/UH9as2S2JqojtDPyDcFJIa+bXzQ/E190At6Vm2CbPPqlxHq/4RmQOj8STxxeBUk/MtRrIQdQUnC3XtAD3+JT8jFgRFHCg+SMTFaGYuWO9hhTq8BKvj7I/Ul3x4tyoPEfo/33tyjiaAy4clrggAKfWTv+qOacyHes9mPeDYqV77m2+YLnM7xhwubLCJ9XzS1uvxtL21LrhHhRYH5VTrEJljMlCmpPl/FgbC+rLfUdm8vVMo2tNDqDl9HkvU09YsBpDfgMC3TxQRBS0dQDOZ+bvKmYUi2hT0jdbFwknS6n3cGYA0fkGhPc+OF8ucGtaYYL76mweuuHLeAWCzbGK0lO3Ez1LhsODijJ3hrWI9NV3tIZmHdcZV3Kx4dOEYUL2dRxs6IOtsaEijtJQlcIQp0dD9WnFKoVU0UXbyjjEzVPU50jPLqB+pzgx6DELW8QaIiPRdZFEfXYGFqLuRoTdzrKOQYNnfhQ04Q1vm4MosUE7E9dskjzBYufApJ6w7XEXfjX2RBrFF5dk/LTUY6dQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: toggl
      namespace: data-hub
    type: Opaque

