apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - namespace.yaml
  # - longhorn-source.yaml
  # - longhorn-release.yaml
  - local-storage-provisioner-source.yaml
  - local-storage-provisioner-release.yaml
