apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-storage-provisioner
spec:
  releaseName: local-storage-provisioner
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner/
      sourceRef:
        kind: GitRepository
        name: local-storage-provisioner
      version: v0.0.22
  values:
    storageClass:
      defaultClass: true
    nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
      - /data/lsp/
  interval: 1h0m0s
