---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
