apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: external-dns
spec:
  encryptedData:
    token: AgBBj/R0UfH2vxLry0Z0IPwnlmH4tEoNDAugN0G/gzGGJSDRfjBd7R5weRRJdXb9Bdtf1KwDcpyN6M8dIKcbg/c7VgMSyTkDhVShPn81qSHbsszeuVxOWKOkQijF4YEfudzb8cVS02vD4v/qLZtIFlGaaQvLpoieVdFYWpu0nOQQqNl30DIxLR8ENonsFv4mlfKVKTK3NGGa5LViMRmheAA/c7aFf8Esy0D1KI1wO3f5TIjcBED2sqaOSRtMgKlpaDxgcf9HrbBPUFct5XJeFdPU2IQobUv3ltgbvQvYYBiDG57T4IJWQ6VmNn+Zvd9nwcZxJYlsvo1XdSD9PpC7y4C2biZI309768YEqAOXePhLLGoUF49IIlAVvf2T/Cdl/2Qpd5BBHrQzWVkmu30YuRQKIWN9Mb9XEOxMYUgS5v95GYKl0Hba5ADNYom30/VvZwHWqouTK1lTdDR2+nyQhDbYhC8lI/I3SmcTbPuHRD1H2TmW2rncwI8S7rhVSkIasWfDTrdv9IJ0nevQmp9hq8E3ROEgqtzjvNFl1rIWRZTolwazKabvaOBUx/26HQKmL79kVP66+icMs92z+DTPWNiaoLC8ofxRXWL0YzKGrGsJMgIlJzdUMzYDiVmoApuSqRopmJ3tXtnTqd4eQU3QgW/eQqnCOqnxsFlIFiz76M0VwJRASq5I/1o1pS+uGe4T+iNrbJQos8MopeswsL3CsDp008O0KpTuyAHLiaNoVjhgTzBySA9g1liv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: external-dns

