apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: external-dns
spec:
  encryptedData:
    token: AgA5/DNjqAhvmBb+lpZgesKXtvc5LesKD1eAlqbi78eyRp0kbRLC/OGK+Ejnbb3+yVoPLk3rNX4yoR8NCTpW7OaGis8a+n/xaxTSq/YBa5lqUDdLouE427IQVqQFxH+cm8sBHxbNqh6rw7JL3P8mTw5/we27bqXootLHaUvahVEc+97y0gsCE4PgVUbP9pgA9hNwDAJsKlyo9jU84yVt4dcGXhWKOgiPLAFnM3zweAlZKcn0tfo1d9/qtmFbpvcDALtBGn2vYJofGN2kV7/VM4ozp2A6KNmeMp3DNw4Tds40fEgnUBX9271JAGUMvgfwHWZFjgm6f2VTISWV936cB5LDi6ODv+UD/Nb95UaL4flJLzcU3lBEWuVFMO5bSW+1a2pmVcQAwg9HlywxyuSDB3rFko0mVry4FF3WeTKeT2sJyXv0NsQLClYn6g3wQ8gxsSdeG6bV0p0LjTEb21QisMNv+Zwa54A8hyVb1SkMen8quhmEi/YKhTJ+U4PZ7VnL9BJ5gHO5YdqXmXFUwxMgZb76zIvIiV0jqAdVDM1XcMxOC0k+WzjK88HjKEiUBySdJQ/K+KJkArskX7338UL0mydq2Ow1MlPfZw8zefvREthU3bHFSqypQqMJb6FtoaFiI3kTn2pu+mWbwfcr+JJD7XrnKt9CXT8YDCF90NHU+ZQTj4CglRP5r7M/4aQmP5E0BRptQvzVS9HbSyxYYeYzNLS1rOVvI/8qU5e67K7nsEXzRhquJbV/n5Yk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: external-dns

