apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: localstack
  namespace: localstack
spec:
  releaseName: localstack
  chart:
    spec:
      chart: localstack
      sourceRef:
        kind: HelmRepository
        name: localstack
      version: "0.5.0"
  values:
    ingress:
      enabled: false
      hosts:
      - host: localstack.kubepi
        paths:
        - path: /
          pathType: ImplementationSpecific
  interval: 1h0m0s
