apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
stringData:
  credentials: |
    [default]
    aws_access_key_id = AKIANONO40NONON0N0NO
    aws_secret_access_key = NOnoNon0N0NOnoNon0N0NOnoNon0N0NOnoNon0N0
