apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
spec:
  encryptedData:
    credentials: no
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
