apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: peerscout
spec:
  releaseName: peerscout
  chart:
    spec:
      chart: peerscout
      sourceRef:
        kind: HelmRepository
        name: kubepi
        namespace: flux-system
      version: "0.0.2"
  interval: 1m
  values:
    env:
      # DATA_SCIENCE_STATE_PATH: s3://staging-elife-data-pipeline/airflow-config/data-science/state
      GOOGLE_APPLICATION_CREDENTIALS: /root/.gcp/credentials.json
      DEPLOYMENT_ENV: dev
      SPACY_LANGUAGE_MODEL_NAME: "en_core_web_lg"
    ingress:
      enabled: "true"
      annotations:
        ingress.kubernetes.io/auth-secret: peerscout-basic-auth
        ingress.kubernetes.io/auth-type: basic
        ingress.kubernetes.io/auth-realm: 'Authentication Required - peerscout'

    resources:
      requests:
        memory: 512Mi
