
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: artifactory
spec:
  releaseName: artifactory
  chart:
    spec:
      chart: artifactory-jcr
      sourceRef:
        kind: HelmRepository
        name: jfrog
        namespace: flux-system
      version: "107.29.8"
  interval: 1h0m0s