apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: kube-prometheus-stack
data:
  alertmanager.yaml: cmVjZWl2ZXJzOgogIC0gbmFtZTogJ05vdGlmaWNhdGlvbnMnCiAgICB3ZWJob29rX2NvbmZpZ3M6CiAgICAtIHVybDogJ2h0dHA6Ly9jYWxlcnQ6NjAwMC9kaXNwYXRjaCcKCnJvdXRlOgogIHJlY2VpdmVyOiAnTm90aWZpY2F0aW9ucycKICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNjBzCiAgcmVwZWF0X2ludGVydmFsOiAzaAogIGdyb3VwX2J5OiBbJ2FsZXJ0bmFtZSdd