apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: kube-prometheus-stack
data:
  alertmanager.yaml: cmVjZWl2ZXJzOgogIC0gbmFtZTogJ2NhbGVydCcKICAgIHdlYmhvb2tfY29uZmlnczoKICAgIC0gdXJsOiAnaHR0cDovL2NhbGVydDo2MDAwL2Rpc3BhdGNoJwoKcm91dGU6CiAgcmVjZWl2ZXI6ICdjYWxlcnQnCiAgZ3JvdXBfd2FpdDogMzBzCiAgZ3JvdXBfaW50ZXJ2YWw6IDYwcwogIHJlcGVhdF9pbnRlcnZhbDogM2gKICBncm91cF9ieTogWydhbGVydG5hbWUnXQ==