apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: googlechat-provider-config
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    values.yaml: AgCQeNhkDcjKxHcPbYqqZBaDhsv4N8SFcbO1umOh/PvWZGJhQElJhqRGi+VfYmmK+iVGPlDQIsm/RC+7fF24tMzb9+WP76ZRA1ZW1snxruT3p46cy0gLIMpHxJKejMBlLEHog+jCZt+sF039iXtweOU75jjgf/xOBxGeGaf6M4Tn15HfichuE9z1/4sG2uzWEPUaYazJqux306EzxW8D7ObyURaN9fAPQLhTcsbdfcWjtwmBA0Y6/oE6Gzg7y14usyA0HB85jINkWKWquv3Frwmy7ileBJ+h2IV/kpjVdN4QcvhHu2kWkR/DEi1ktUqKbKXjctKOZO2qbcxBq5JnH8jJQ4xYrDWY4XiciSqb7/Xp4SvP/mwQQLjzD5yKa0V1BVfruGgNTbAVNopEOxTbuQ1PdAx0pC7Ex5mY+9P150at+aZTDI7Nqy+H4lwY+rEOMBZ1Q11ofiBtqSTF5kR/nGbUnvDWBkdAbzDRxgViBGA13jz810RaU8fMsHmjQvsRkGtq5qNebDxoaYJNBWn8P6tZDLz3zZAgu+jhm3onhmjfzWNftKaBTSnpLVczDxFqfIgJMaiDrQJPXinALws3bYV9ee7sNGUi/9kWkhPi7nOuQzWwCiU/axNsJIS2cn1MinkkJiYC7EHLpo3sRy72oyBebRLJTrhI6GQOIxHRJ/4q2aqnWQBuTJSSIZaZfeP2sadUvCMmRUBPVR+lTIRBbS0K35H9nyuKutdBIn9twmQlCOjPb6A8QyQ4sIacVctOgsvCmr75qIMNwgB2bANrhtG/pWI5TqymKUJDXWZ6PwRUJrQWG3Kkv8uaYDrM9zOmkaDHCCiJGOma73VOlhO4AVZwqj55ALxMRki75M51fjV829xdqvgGfEq5snue0qhAMXdK+St6JeJQMUw0oEp1+rsLI6Dx8RKHEWVX0DbTs77UWwR9/Yb77U4hXw6S3EJp590hJ4Woq7dAInarlmFOHu+jZVxOdI0w+8ibF4I=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: googlechat-provider-config
      namespace: kube-prometheus-stack

