apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: "3.8.2"
  interval: 1h0m0s
  values:
    defaultArgs:
    - --cert-dir=/tmp
    - --kubelet-preferred-address-types=Hostname
    - --kubelet-insecure-tls
    - --kubelet-use-node-status-port
    - --metric-resolution=15s