apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mattermost

spec:
  releaseName: mattermost
  chart:
    spec:
      chart: mattermost-team-edition
      sourceRef:
        kind: HelmRepository
        name: mattermost
      version: 6.6.9
  interval: 1m

  values:
    mysql:
      image: mariadb
      imageTag: '10.8'
      mysqlUser: sampleUser
      mysqlPassword: samplePassword
    ingress:
      enabled: true
      tls:
      - secretName: mattermost-cert
        hosts:
        - mattermost.aubrey.org.uk
      hosts:
      - mattermost.aubrey.org.uk
      annotations:
        external-dns.alpha.kubernetes.io/target: kubepi.aubrey.org.uk
        cert-manager.io/cluster-issuer: letsencrypt
    persistence:
      size: 5Gi
    image:
      repository: ghcr.io/scottaubrey/mattermost-team-server
      tag: 7.1.2
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          version: v1
          kind: Deployment
          name: mattermost-mattermost-team-edition
        patch:
        - op: remove
          path: /spec/template/spec/initContainers/0