apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mattermost

spec:
  releaseName: mattermost
  chart:
    spec:
      chart: mattermost-enterprise-edition
      sourceRef:
        kind: HelmRepository
        name: mattermost
      version: 2.6.10
  interval: 1m

  values:
    mysqlha:
      enabled: false
      mysqlUser: sampleUser
      mysqlPassword: samplePassword
    ingress:
      enabled: true
      hosts:
        - host: mattermost.aubrey.org.uk
          paths:
            - path: /
              pathType: ImplementationSpecific