apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mattermost

spec:
  releaseName: mattermost
  chart:
    spec:
      chart: mattermos
      sourceRef:
        kind: HelmRepository
        name: mattermost
      version: 6.6.9
  interval: 1m

  values:
    mysql:
      mysqlUser: sampleUser
      mysqlPassword: samplePassword
    ingress:
      enabled: true
      hosts:
        - host: mattermost.aubrey.org.uk
          paths:
            - path: /
              pathType: ImplementationSpecific