apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: "4.2.4"
  interval: 1h0m0s
  values:
    controller:
      watchIngressWithoutClass: true
    # controller:
    #   ingressClassResource:
    #     name: internal-nginx  # default: nginx
    #     enabled: true
    #     default: false
    #     controllerValue: "k8s.io/internal-ingress-nginx"