apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-ingress
spec:
  releaseName: traefik-ingress
  chart:
    spec:
      chart: traefik-ingress
      sourceRef:
        kind: HelmRepository
        name: kubepi
        namespace: flux-system
      version: "0.1.0"
  interval: 1h0m0s