apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-ingress
spec:
  releaseName: traefik-ingress
  chart:
    spec:
      chart: traefik-ingress
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      path: ./charts/traefik
      version: "0.1.0"
  interval: 1h0m0s