apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sciencebeam-texture-sciencebeam-biorxiv
  namespace: prod
  annotations:
    fluxcd.io/automated: 'true'
    filter.fluxcd.io/chart-image: semver:*
    filter.fluxcd.io/grobid: glob:*-dl-no-word-embeddings-wapiti-citation

spec:
  releaseName: sciencebeam-texture-sciencebeam-biorxiv--prod
  chart:
    spec:
      chart: ./sciencebeam-parser
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: sciencebeam
  interval: 1m
  values:
    image:
      repository: elifesciences/sciencebeam-parser_unstable
      tag: "e9a9cf54fbc8f0b043dcf2f530e348afba78d4bd"
    env:
      SCIENCEBEAM_PARSER__XSLT__TEI_TO_JATS__PARAMETERS__ACKNOWLEDGEMENT_TARGET: "body"
      SCIENCEBEAM_PARSER__XSLT__TEI_TO_JATS__PARAMETERS__ANNEX_TARGET: "body"
      SCIENCEBEAM_PARSER__PRELOAD_ON_STARTUP: "true"
    ingress:
      enabled: "true"
      hosts:
      - host: sciencebeam-texture.elifesciences.org
        paths:
        - path: "/api_biorxiv(/|$)(.*)"
          pathType: ImplementationSpecific
      - host: sciencebeam.org
        paths:
        - path: "/api_biorxiv(/|$)(.*)"
          pathType: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /api/$2
        nginx.ingress.kubernetes.io/proxy-body-size: 120m
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    resources:
      requests:
        memory: 3Gi
      limits:
        memory: 8Gi
    startupProbe:
      failureThreshold: 6000
