apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: sciencebeam-texture
spec:
  interval: 1m0s
  ref:
    branch: implement-newer-kuberenetes-ingress
  url: https://github.com/scottaubrey/sciencebeam-texture
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
