apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: editor
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: db
      protocol: TCP
      name: db
  selector:
    name: database
