kind: Service
apiVersion: v1
metadata:
  name: traefik-metrics
  labels:
    app:  traefik
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - name: metrics
      protocol: TCP
      port: 8888
  type: ClusterIP
