kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress
  labels:
    k8s-app: traefik-ingress-lb
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:2.5.5
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        - name: metrics
          containerPort: 8888
        args:
        - --providers.kubernetesingress=true
        - --log.level=INFO

        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443


        - --entryPoints.traefik.address=:8080
        - --api=true
        - --api.dashboard=true
        - --api.insecure=true

        - --providers.kubernetesingress.allowEmptyServices=true
        {{ if .Values.traefik.ingressClass -}}
        - --providers.kubernetesingress.ingressclass={{ .Values.traefik.ingressClass }}
        {{- end }}

        - --entrypoints.metrics.address=:8888
        - --metrics.prometheus=true
        - --metrics.prometheus.entryPoint=metrics