kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-https
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - name: web
      protocol: TCP
      port: 443
      nodePort: {{ .Values.traefik.httpsPort }}
  type: NodePort
