apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dummy
  namespace: journal
  labels:
    app: api-dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-dummy
  template:
    metadata:
      namespace: journal
      labels:
        app: api-dummy
    spec:
      containers:
      - name: api-dummy
        image: scottaubrey/elifesciences-api-dummy:632c69209eee593facdcea21c3d202cfeeee85e1
        ports:
        - containerPort: 8080
