apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy
resources:
  - namespace.yaml
  - secret/oauth2-proxy--kubepi-cluster--google.yaml
  - oauth2-proxy-source.yaml
  - oauth2-proxy-release.yaml
