---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 1m
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: 6.2.7
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      interval: 1m
  values:
    config:
      existingSecret: oauth2-proxy--kubepi-cluster--google
    ingress:
      enabled: "true"
      hosts:
        - auth.kubepi.aubrey.org.uk
      tls:
      - secretName: oauth2-proxy-cert
        hosts:
        - auth.kubepi.aubrey.org.uk
      annotations:
        external-dns.alpha.kubernetes.io/target: kubepi.aubrey.org.uk
        cert-manager.io/cluster-issuer: letsencrypt
    extraArgs:
      whitelist-domain: .aubrey.org.uk
      cookie-domain: .aubrey.org.uk
    replicaCount: 2