---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns

spec:
  interval: 1m
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 1m
  install:
    remediation:
      retries: 5

  values:
    replicaCount: 1
    txtOwnerId: kubepi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    provider: cloudflare
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api
          key: token
    domainFilters:
    - aubrey.org.uk
    sources:
    - ingress
