---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calert
  namespace: kube-prometheus-stack
spec:
  interval: 1m
  releaseName: calert
  chart:
    spec:
      chart: ./contrib/helm/
      sourceRef:
        kind: GitRepository
        name: calert
      interval: 1m
  values:
    templates:
      message.tmpl: |
        *({{.Labels.severity | toUpper }}) {{ .Labels.alertname | Title }} - {{.Status | Title }}*
        {{ range .Annotations.SortedPairs -}}
        {{ .Name | Title }}: {{ .Value}}
        {{ end -}}
  valuesFrom:
  - kind: Secret
    name: googlechat-provider-config
    valuesKey: values.yaml
