---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calert

spec:
  interval: 1m
  releaseName: calert
  chart:
    spec:
      chart: calert
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: calert
      interval: 1m
  valuesFrom:
  - kind: Secret
    name: googlechat-provider-config
    valuesKey: values.yaml
