---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calert

spec:
  interval: 1m
  releaseName: calert
  chart:
    spec:
      chart: ./contrib/helm/
      sourceRef:
        kind: GitRepository
        name: calert
        namespace: kube-prometheus-stack
      interval: 1m
      reconcileStrategy: Revision
  valuesFrom:
  - kind: Secret
    name: googlechat-provider-config
    valuesKey: values.yaml
