apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
      version: "3.4.5"
  interval: 1h0m0s
  values:
    resources:
      requests:
        memory: 512Mi
    replicas: 4
    persistence:
      size: 5Gi
    ingress:
      enabled: false
      path: /
      hosts:
        - minio.kubepi
