apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    credentials: AgCEtVhuZok2ajkpiXU5vAedNNwYNeu177qZkUBBUe64GMb6Arz25+eCXrFFzKeCFp6M0cKPulsUb/eGXT2sb9laqeD2TbrY7+9guoV+8UOQ8EkoG6AEtbQ7L/MQ2pa1QXED8UUTIHBDFAIHBJZ1TLGvbDZMS2CCvxXYAw9LqylXiCl2w8+Olh+vvrbpjTasj8ObmuW/gzPsCWdylBtn7ui5gSXWkrprlZEa1K2LpScJpD9kyNQoT0Dv6M51GAdS4XeDv87DNpNIwKRFmC7Ub5aJc3fDC1Q9+bbwIJ3uu4hlr8ORnMfxTOqpojVNPQRcIlxbc1sdk3CIy2tMVGGSC9uAuwIxr6+12BIdeOARmGLlq7NOFwopnLThUGRuiKgWlWBvumnnG//XgGQFwHecaAbN8Pk6XGgpOMOCNzH8kqF8wkSGIZIIUzKE/MuLvzQOysxWmsXeGAgPJpMOkVc/YMbzUrMJXX4aTsZO48OGEsAgkdKbivanS6ppcz+dgu8Fb8L0HQWFur7cbhl1hKeNaGHHqV8KeHTvdMXQPZu9heGcVTyd89uY5Bv+bMMknS4hDLbMj0FIlujZ+w4QmOPKazH5TKmt/6Cm6B+0NpSJG8empwePV31mpT8tloC2Q36zvn2nEf+m/sudzRBJpqJx1gd1tP8P5YLbVIICu4sTtO7RtKneeI8dx1u0LBvqmDlqoXI6vFw=