apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    credentials: AgBbpVTvF5NKsXB3n3XEN+H+jo8ljr669MeY6Nl0ZhIhOBrmMcdgfit2xHfIK4OM6laAk4ePe7BneLWsTJwrnsySI30s+NWs5u911V1S+/zTHhKcN1Ng6EPfqbJXj8bK+Fp+roSlJrcgf2gepG0aXQgfemEQLjgmgwprfZYqchSjvEiZ4cwyHxruMytD/ZuEl9KpVMdCjpyTX2X71nq4qcdbsHuZhaYpjizdcD5H31WphOzeDGSRAovislP8b6t6WvrHtmGSXKHLlpGrXxwU5yQ+gOgs47t8hx63OV7BVbvEU8xADx5zc/Xj1/CSBiL7ktp20P3Ndr5LUFuP1x2Pvx6AcBnbM3CbhTNf8mXp4LvRgIoCppwCG1304GhnhhTt/f54AGC2FOvJA/UF0qetqnlHzOBmqJTgInb8J3vWE5C6zwZqT3eqm+GfCGAuBNCBSMcZTlIiouM9ZCcVV6gbHFPHFHnllcBaqpEssQhHFaN4bZ9pK4qHzHohFHmaFANNRosGoDuemEvyBR5bXqY7hF12UcoBF8BSGPNevI7GU9mXodMi0NDzsxosfTOwvW4sddB7hhs3gr4Chg1MqZEdP9FIwKF4pV4QIMKeY5j+ekKtjCS7mXUrZgDISsUO+WBtO6XaZlSGPF3zvHGHlTveceDpB+9+skj7RT4SwurEeavuVB4ku2pnqRZSgSgEwFVQ7YxkwEgw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: peerscout
