apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    foo: AgBtcAluEGCpzDB14AZmyBAS8OQz3dz4rdrQXyyjGqHzkYPwI50agn/8Qerln6RByo2latzKwM8FKTo2aqNYzVddH1VgIMCuNbDnjC2/l4YOLpJSBIasFtN8wGaCj0c7o22quCOd2cvNTtUj0CWl5INRqVlXTngKgzrKbQOTwlo6RQPfwKxO7llqzvieFuU6FU978ZNVmmkbne2jp4u+xfnNgGhefDNtBUbbaozuExT/iM/z/0PEplRvRoxNdM7LE212BM6q9csX03fwgWdmJkEAKj/R2wgrNM9VX2bMyVXVyIalQzJ0b06U0xB2NpJYsvKSMbTybfaa6fdtaFDFYyZI/8K7nffUEeHtqIAabS/9NgQcd3St8Xl3+XH+kkMFKbPKhKmhJTVSwDXkdzn9CQBvb7glVwbz0OEcT7cKNv1593O4M+Coff0WU5fo/fLRAvVaSzuVu9agRXAXQi6OpbLHo/DTRscKRV9e7zMHzMRaCxeHrGggLz/RlxRF0d08TzoOGr4eR8ot9Lez1Gbm4+DgyVHGuUmiyu0YJsg0hUgLSEw3sFle3FgTM8Zh41suL91MkNKercaFraz4cNE6zfQYy8ka8CY65Q8vj6e3pAuSyksmUNFwA+d2YFHtuIr7WrKCkYWJzWehJ5USGa7gg4mPy/dcw/qsOoiw3QuYywbwlQfniJad90sCZHM+rv2Gpc1Ku+5f
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default

