apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    foo: AgBjFBYgiNZFUGt0ASHVdPOd3XfJUF9hnSkv2sNvi1XQjuizw8XuRFzr55T5TSbzeBIyhiq8zHcpMV20xbIbfZOQHgD75iJn9jfVxN1M6H5tiVwQCnUg8qWxTCwy/F/lJT99dlK/AAf3KpWb7UtXf/LkTbPJJPqeQVdyGu89Vep9aqre+EezyZkx/gFXjQZHQ8CKmP7yVzOCpMcKbpsvGsJ3IkvftOWBiGC5iKqtm7T2WV5tcJJqkk2O8953mNsPiTGiTfTIOaIrtXsvLwf2jjQp44oUihpdij3KYseeo82SYl2EZ3PNzH9P6JZBZh8/4sQwvFz64oznNTBTeF2IPvvw6rj6TVcHCWz2QAMtcVuu9uMF/wG1cBdl8E5oQq5Kg2goW0jo5IRmS/t7OmKIRI1F/oJwHYwMsuW0djdMW1AhV6ZjaSgS2tAF9rgxZCD6PTnEq2Nptz2J1IpZEwSZnFC3H9jXsVYbynw0aAB5PIR3l7SEn7XxHUcEDhTAK/YAwdA3HpVJhlg5u457T1i1Vmym7eWSAmxnq4imOIxnARFa8AduEzKClkHyQD53qe043CmeYgnjsaleDtnH5M6AZ9BYP7kVf1WrgcJD29BCw4ugz+TYWNZ9yNZMlLwdlie6v4lNVSc2i+bSytNn8R0QPd26BZeOoZUviGSIXlws324IN1NBdVwoskWloiKf3NdX1tfPChbB
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default

