apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAIYLO+Btb0XO182lGgUUvuy9dS//bJ9G+CkQlm4YVjpxIOuOT7dAsy2buW10oDlbiWn9jyHWWpPG7aODAHZ9h9ihhjHwGUBWI+0vWuZ4ATzMDqxT3QY9xZgAdZN1H8nkWPsUjSzMhSFqeqpJuH3QlT7IQdL3urpCDWrSB9rc9reh9ZfTrcRqx7iqKUZdud+pmkl7CT+PMzNtFED9KPiz2906DWrbKgr9SZEq6zUBUnwnAQP32X8pUD+42ZzS61b6Q9vQQwfAWtFtv55CWqf9LH3yS/5izXkNWptUQN/wzZYsgDz7w6jzgiS57eSnrlLI2L9T1GJsp/aQDgS3oeGBgkqIclkXGnnDG4XBuAM980NCItBZjNhIfGgHcPp7QLyqDz0Sopj9bVV/y/UgXcSsj4rCDF4wsicWWfJWpNpuKymL+8I9KWD2s0C4O1nKw2fv6NFZ3XTqyQnHv38cWBhRzchOsE4UCe0nATP+bGubRTmPk4VZlBdbNCGyH4QQcc1ME82Lbir+H0kOJaqEH1Wzm0l03JJlb3nvnVylSIARW65P7EVO2MNTfCOjxG8sdd6azxYznZ1tK7vY8uHMBT7xeCuIYRhkjhwxOeDtO513yPNcdjNhVYqLHg0IlTK/XiaQO2R4KZEUjAICLJbPXq47FyigY9J5rCETO2VXQDNbphV9aq0uZCJSfBGn/g7JMWqtoFtAt2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gcp-credentials
      namespace: peerscout
