apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    foo: AgCBmlQphwZBfjv9ak9aaJfu+4OxdFQ57m2vW+UVYmYX5++SCrkv2UerdkmtK4oAUNUvPh1imX7As8xJFIoKuJhlWu6pAlWdccxhaV7be5empTKtpR+qhRJZu3jpOjJfLauGcoHtf7iJIp8pjGPGMJZCS7u0XYaIvpSRatDlsMMC+k0zc8ujVrY+TR0M7iiZ8MdanMqooxwr8/NlK4rKrXEswogHDgYLwgWm7/3L1iOUj2EJSEYnIAsZLGqvRp2cAZpvip65N+hsZcdti7OjOq4mH/oIHa7aSULY7Qsr9Uyucvih6Pks9EmhPwuawCfFrHHbie07u0Yc7fx7Wc22qNOBpFHW2XD+2HsQzyB9oZswNfuRDKxd3x/f6Tk0mCsmaJpPR19COZUfRbd7mOWYilt4fHBhnsy6VAQgxWTkNMlKA5iV5/DjHhMa4K2hYZkSa2hi0zfRgs/X6paaFnSWMzSoBwkYgqLaWEvhy2ynoKk01O08VEbYXEN7frHZET/Y0WFkn+iZxCUdTwch0lH/LySnPWMcmbQc/8IdHBYld2MUGPglj2KLMk8axVgH8NxLupjkcHUS7K2gSpRCIjBqmLrEDJrXKvzfjGxLQ5T94aHg/dTFE2Dr9lBvb4haaRdVtpNJyJ66vmVC69ag/+xkneTtg4UtOzAirCcuv/0wcUKSyO2kTZaMsM+2qnIWndGf9pKTnVQ/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default

