apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gcp-credentials
  namespace: peerscout
spec:
  encryptedData:
    credentials.json: AgCguBpmeGQOPHGrZQWl4REIu3YhIIEG+e1GqzvmDWbHNh46a9uhH4nCnOCk6+rmfxxCaikjo851pGPEeaej5GjrMmoxs1VayUmIH2ZDQylv4Q5X/zx0xlqXyB2FiHI9mXi0yDD/vb5ih8xcwARzEGum52PwCxZFuQ1/9cwfF3y5Y6Y1tJeTMk5BLSlGqwIdqM5HunLbiG9e/mIElm4+APRy2Fs5K3cNXB7SmVGayOXq3MztYN1fA2vFVzDg947zBWtHu1u7qlmJYO02sgB9axM8LzCaMQPxQZvWPx9jIbXRV3Mu5rusGYoSTwXop/RMa/8g2cDPre+tEW1uXEqA/74qJSEaerihsm9veCfZY44q3nhqO6xzVa+l21pIt2rRUd+89LJJifIoHKcz+US971pTbR1wJGy68Q3ua/tGZfjtZMTKbzkzy+RF25LaGn/VW8x+Tb8SvU0vyUwrejlA2xuQC0ZdVXtEuZcxkaOEa9wnP8Pr10j987BKDcbDaqJdwFMVJJvyFk0NuaauGPWS5Lf3syLS6JxaeBqJx+NBkP+YUDyA3O8sbY/1Jta8MJV+FenUh/nkFZlG1pUgOt1osxQ3Rs/VnAe4d0ibo1VF1I2srWvD2OxRK/Mtz6IjLHayfk6rWZ3/b10H2YN9lXrDzpoey0grb5v/hszke8g6k9XFl9RfXOcV/e+vlVY3fv9OeVHy6t2T
  template:
    data: null
    metadata:
      name: gcp-credentials
      namespace: peerscout
