apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../base/sciencebeam
  # - ../base/basex-validator
  # - ../base/data-hub
  # - ../base/editor
  # - ../base/reviewer
  - ../base/journal
patchesStrategicMerge:
