apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy--kubepi-cluster--google
  namespace: default
spec:
  encryptedData:
    google-service-account-json: AgA4kV4EgEewlRfYfFTSU8/BQZCgudKrYi85KEIir2FU5z73BLP7HwgyMOAzf8YbqjRumzX835SRVacaohY13Pckv6wattz3y6IO+aHt8vzRm7K+g23dDfAdZRe9uVUl1ytF4DXsEY0v3y6Aqyg031OSdhY6j4f644MZu5uarLO+b+JVujP12DfzAw7V/GswkFpuMOYy4dJvbqfEIghh2AjNtwC0WVIINxIdFHuLOTVQf1OyP35UKxYnyzCVg7Zh98Ir5IJ1SsCUl5tf9GiEtC/JeJLjsNw/hayMBNHsw3aB+TCFTT+bb1QUvZkgsMpNhrLjupXEYdnJ6x4tOJSMpS4b02JeKQ3Y/ox5q5Kyx/HPFbaZ/xrf+gGE2b286JFKSEUOQpBsrS0UzBiMCbxWiqdnYb7ud/zMNBKEH87oODb4PIFUJ2vCJ3BV4OcBvoiq3GcPaINSaSYPWk3E6hTLY55/L77QXbIH/cWod/iMkikKU3nfvSwqaLAlaDXG78AfB5aOPUfsV1wUbKDL0dIJR4iAI45/HJ5anGJguPCcfpvMd6N0rrzzImwVjadoaRGuPsat263sUR38s4GLn8HwphOAzNINj1+r/YMtc62qGKsQPij1lJXzxPzOlaGAe08B8kcPU69XQaRz570g/fW0D4ZDX1vCJb0MmWfTRmKEd6Z8ViGy3TPfy3Y+5+FEx+Vo6hsGSIVMLlRC1CUJlzKkZuf0xJHo/J0BModIqtyvWY+ANKsasD5y/6GBaKzWfUi1zMIUxpnWbtGeSgjgLs4vlYiutp1h1HfUKhsACEm1xdlppZnXN8dqpHUebLI4ysey7jYE/c1YhtTzdAgqnwns5Bc7eUM+ZlX+l3S4ExzWQXaxbJHSf2HAzxD8bq/H7iY3CIdPc7ke2w1j7+EvwkD4VMycP0tzK8/8rAntk2rJwqbxDU6xdG3fqbL4kkATvjHAAVp5IXMmXMYckaftQj1rlXAAXeHQsN4u6AIBx8QfjVs0NJlwa3E7Q3rjXG6vI/mDn9Q7Ld56vMxV/64Stsh3rbuqtQU9DXIkAtMKVJ44YKQPxY9oGU6Wk3NttFC1N0AdXE0xPZegdNntVjtLDrRm0NrBlavAjzMgMyL7FwH06zJASh7uWf+/eUITPRDd/wyTRHpe7XYtEygl7NMHKUmKs021apckU5jZVhytC8Z9dfp+9/PGkD4cIlXXBGxFXfaM2AoMn9Nz867F4gnLL+y9oKWZmRlR8cjdbvZT6Zs/oRk2uEgWImXBONiHZLlMZ6QG6yPWeKKqh5JECaCcj3GjkGI5t/XtCJxA7lL4zAQkYBx/MZpuRuZ06UojeXEK0BD9S+nvQEPS7Wop4xfZrYuAvggRqgDb+7ExGt67DeiVm2P4TlQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: oauth2-proxy--kubepi-cluster--google
      namespace: default

