---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-crds
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: metallb
  path: "./config/crd"
  prune: true