apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server
  - metallb
  - ingress
  - local-storage
  - longhorn
  - sealed-secrets
  # - minio
  # - localstack
  # - featureflags
  - external-dns
  - cert-manager
  - oauth2-proxy
