apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: basex-validator
  namespace: basex-validator
spec:
  interval: 1m0s
  ref:
    branch: implement-newer-kuberenetes-ingress
  url: https://github.com/scottaubrey/basex-validator-formula
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/basex-validator/
