apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unleash
  namespace: featureflags
spec:
  releaseName: unleash
  chart:
    spec:
      chart: unleash
      sourceRef:
        kind: HelmRepository
        name: unleash
      version: 3.0.3
  interval: 1m

  values:
    postgresql:
      image:
        registry: ghcr.io
        repository: zcube/bitnami-compat/postgresql
        tag: 14.4.0-debian-11-r18
    ingress:
      enabled: true
      hosts:
        - host: featureflags.kubepi
          paths:
            - path: /
              pathType: ImplementationSpecific