---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: certmanager

spec:
  interval: 1m
  releaseName: certmanager
  chart:
    spec:
      chart: certmanager
      version: v1.8.2
      sourceRef:
        kind: HelmRepository
        name: certmanager
      interval: 1m
  install:
    remediation:
      retries: 5

  values:
    installCRDs: false